# docker-compose.yml
version: '3'
services:
  docker_dev:
    container_name: docker_dev
    image: docker_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    ports:
      - 6001:6001
    working_dir: /app
    command: python app.py
    
    